# LSTM on IMDB Sentiment Analysis

这个文件在IMDB上进行情感分类，练习torchtext等的使用，熟悉训练流程，并测试以下模型的表现：

* LSTM

目前的进度：

* 完成，效果不佳

问题：

* 迭代器并没有shuffle?
* torchtext怎么使用预训练词向量？
* RNN训练时要使用packandpad吗？还是仅仅pad就行？使用了之后还需要让长度相近的在一起pad吗？
* 后续使用BERT可能要用transformer或者allennlp？

参考：
* [torchtext使用--简单的IMDB情感分类](https://blog.csdn.net/weixin_43301333/article/details/105744602)

## Requirement
* spacy==3.0.3
* torchtext==0.6.0

## Import

In [31]:
import torch
from torchtext import datasets
from torchtext import data
import numpy as np
import random
from torch import nn,optim
from sklearn import metrics
import torch.nn.functional as F

use_cuda=torch.cuda.is_available()
device=torch.device("cuda" if use_cuda else "cpu")

## 供调整的参数

In [39]:
lr=1e-3
bs=64
d_embed=100
d_hidden=256
d_output=2
dropout=0.0
max_epochs=10
require_improvement=1

## 数据载入和处理

在载入和处理数据部分采用了torchtext库。

In [8]:
TEXT=data.Field(tokenize='spacy',tokenizer_language="en_core_web_sm",batch_first=True)
LABEL=data.LabelField(dtype=torch.long)
train_data,test_data=datasets.IMDB.splits(TEXT,LABEL)

aclImdb_v1.tar.gz:   0%|          | 0.00/84.1M [00:00<?, ?B/s]

downloading aclImdb_v1.tar.gz


aclImdb_v1.tar.gz: 100%|██████████| 84.1M/84.1M [00:04<00:00, 20.5MB/s]


在这里可能会遇到报错，提示不能载入*en_core_web_sm*。

输入命令（需要翻墙）即可解决
> python -m spacy download en_core_web_sm

**下面展示样本数量和一个样本。**

In [10]:
print(f'Number of training examples: {len(train_data)}')
print(f'Number of testing examples: {len(test_data)}')
print(vars(train_data.examples[0])['text'])

Number of training examples: 25000
Number of testing examples: 25000
['Zentropa', 'has', 'much', 'in', 'common', 'with', 'The', 'Third', 'Man', ',', 'another', 'noir', '-', 'like', 'film', 'set', 'among', 'the', 'rubble', 'of', 'postwar', 'Europe', '.', 'Like', 'TTM', ',', 'there', 'is', 'much', 'inventive', 'camera', 'work', '.', 'There', 'is', 'an', 'innocent', 'American', 'who', 'gets', 'emotionally', 'involved', 'with', 'a', 'woman', 'he', 'does', "n't", 'really', 'understand', ',', 'and', 'whose', 'naivety', 'is', 'all', 'the', 'more', 'striking', 'in', 'contrast', 'with', 'the', 'natives.<br', '/><br', '/>But', 'I', "'d", 'have', 'to', 'say', 'that', 'The', 'Third', 'Man', 'has', 'a', 'more', 'well', '-', 'crafted', 'storyline', '.', 'Zentropa', 'is', 'a', 'bit', 'disjointed', 'in', 'this', 'respect', '.', 'Perhaps', 'this', 'is', 'intentional', ':', 'it', 'is', 'presented', 'as', 'a', 'dream', '/', 'nightmare', ',', 'and', 'making', 'it', 'too', 'coherent', 'would', 'spoil', 'th

有25000个训练样本和25000个测试样本，尽管这个数量比不太符合要求，但是这个任务比较简单，我们就这么来。

一个样本是一个字典的形式，'text'中含有分词完毕的单词列表，'label'中含其标签（pos或neg）。

**下面我们需要把训练样本中再分一些出来作为验证集。**

In [11]:
#确保每次分割相同
SEED = 1234
np.random.seed(SEED)
random.seed(SEED)
torch.manual_seed(SEED)
if use_cuda:
    torch.cuda.manual_seed(SEED)
    
train_data,valid_data=train_data.split(split_ratio=0.8)

print(f'Number of training examples: {len(train_data)}')
print(f'Number of validation examples: {len(valid_data)}')
print(f'Number of testing examples: {len(test_data)}')

Number of training examples: 20000
Number of validation examples: 5000
Number of testing examples: 25000


**下面我们需要建立字典**

In [12]:
TEXT.build_vocab(train_data)
LABEL.build_vocab(train_data)

d_vocab=len(TEXT.vocab)
print(f"Unique tokens in TEXT vocabulary: {len(TEXT.vocab)}")
print(f"Unique tokens in LABEL vocabulary: {len(LABEL.vocab)}")

print('最频繁的20个单词：')
print(TEXT.vocab.freqs.most_common(20))

Unique tokens in TEXT vocabulary: 108710
Unique tokens in LABEL vocabulary: 2
最频繁的20个单词：
[('the', 232441), (',', 221500), ('.', 189750), ('and', 125690), ('a', 125534), ('of', 115490), ('to', 107557), ('is', 87581), ('in', 70216), ('I', 62190), ('it', 61399), ('that', 56406), ('"', 50837), ("'s", 49935), ('this', 48384), ('-', 43188), ('/><br', 40664), ('was', 39911), ('as', 34825), ('with', 34402)]


测试和验证文本中可能出现训练集中没有的单词，另外在训练时为了满足批量输入需要将所有或一个批次的文本长度对齐，因此上述字典的建立中会自动加入特殊标记_&lt;unk&gt;_ 和*&lt;pad&gt;* ，用来表示未知字符和填充字符。

字典长度比较大，可能需要去除一些，或者使用预训练词向量初始化。

**下面我们需要建立迭代器**

In [22]:
train_iterator, valid_iterator, test_iterator =data.BucketIterator.splits(
    (train_data,valid_data,test_data),
    batch_size=bs,device=device,shuffle=True)

#测试
for x in train_iterator:
    print(x.text.shape)
    print(x.text)
    break

torch.Size([64, 1084])
tensor([[   66,    14,    24,  ...,     1,     1,     1],
        [70935,    17,    13,  ...,     1,     1,     1],
        [  597,  1878, 13864,  ...,     1,     1,     1],
        ...,
        [   11,    77,   826,  ...,     1,     1,     1],
        [ 4839,    16,    29,  ...,     1,     1,     1],
        [   11, 12494,     8,  ...,     1,     1,     1]], device='cuda:0')


值得注意的是，**迭代器中的文本已经被转换成了序号**，torchtext内部具体怎么实现的不清楚。


## Model

定义一个LSTM模型。

In [40]:
class simple_rnn(nn.Module):
    
    def __init__(self,d_vocab: int,d_embed:int ,d_hidden:int ,dropout:float,d_output:int,vectors=None):
        super(simple_rnn, self).__init__()

        self.d_hidden=d_hidden
        self.embed=nn.Embedding(d_vocab,d_embed)
        self.rnn=nn.LSTM(d_embed,d_hidden,batch_first=True)
        self.fc=nn.Linear(d_hidden,d_output)
        self.dropout=nn.Dropout(dropout)

        #self.init_weight(vectors)

    def init_weight(self,vectors=None):
        if vectors is not None:
            self.embed.weight.data.copy_(vectors)
            
        initrange=0.1
        self.fc.weight.data.uniform_(-initrange,initrange)
        
    def forward(self,x,hidden=None):
        # input:(bs,1ength)
        
        embeded=self.dropout(self.embed(x)) #(bs,length,d_embed)
        
        if hidden is not None:
            output,hidden=self.rnn(embeded,hidden)
        else:
            output,(hidden,_)=self.rnn(embeded)
        #output:(bs,length,d_hidden)
        #hidden:(batch,1,d_hidden)

        assert torch.equal(output[:,-1,:],hidden.squeeze(0))

        return self.fc(hidden.squeeze(0))#(batch,d_output)
    
model=simple_rnn(d_vocab,d_embed,d_hidden,dropout,d_output)
print(model)
if use_cuda:
    model.cuda()

simple_rnn(
  (embed): Embedding(108710, 100)
  (rnn): LSTM(100, 256, batch_first=True)
  (fc): Linear(in_features=256, out_features=2, bias=True)
  (dropout): Dropout(p=0.0, inplace=False)
)


测试一下能否跑通

In [28]:
optimizer = optim.Adam(model.parameters(),lr=lr)
criterion = nn.CrossEntropyLoss()
if use_cuda:
    criterion.cuda()
with torch.no_grad():
    for batch in train_iterator:
        x=batch.text
        y=batch.label
        if use_cuda:
            x.cuda()
            y.cuda()
        print(x.dtype)
        print(y.dtype)
        preds=model(x)
        print(preds.shape)
        criterion(preds,y)
        break

torch.int64
torch.int64
torch.Size([64, 2])


## Training

In [34]:
def train(model, train_iter, dev_iter, test_iter):
    model.train()
    optimizer = optim.Adam(model.parameters(),lr=lr)
    criterion = nn.CrossEntropyLoss()
    if use_cuda:
        criterion.cuda()

    # 学习率指数衰减，每次epoch：学习率 = gamma * 学习率
    # scheduler = torch.optim.lr_scheduler.ExponentialLR(optimizer, gamma=0.9)
    dev_best_loss = float('inf')
    last_improve = 0  # 记录上次验证集loss下降的batch数
    #writer = SummaryWriter(log_dir=config.log_path + '/' + time.strftime('%m-%d.%H.%M', time.localtime())+'_'+which_data+'_'+which_model+'_'+which_task+'_'+exp_number)
    
    for epoch in range(max_epochs):
        train_loss=0
        train_correct=0
        # scheduler.step() # 学习率衰减
        for i, batch in enumerate(train_iter):
            optimizer.zero_grad()
            x=batch.text
            y=batch.label
            if use_cuda:
                x.cuda()
                y.cuda()
            outputs = model(x)
            loss = criterion(outputs, y)
            loss.backward()
            optimizer.step()
            #训练集的准确率
            true = y.data.cpu()
            preds = torch.max(outputs.data, 1)[1].cpu()
            train_correct+=(true==preds).sum()
            train_loss+=loss.item()
        train_loss/=len(train_iterator)   #train_loss
        train_acc=train_correct/len(train_iterator.dataset)   #train_acc
            
        #验证集
        dev_acc, dev_loss = evaluate(model, dev_iter)
        if dev_loss < dev_best_loss:
            dev_best_loss = dev_loss
            improve = '*'
            last_improve=epoch
        else:
            improve = ''
        msg = 'Epoch: {0:>6},  Train Loss: {1:>5.2},  Train Acc: {2:>6.2%},  Val Loss: {3:>5.2},  Val Acc: {4:>6.2%} {5}'
        print(msg.format(epoch+1, train_loss, train_acc, dev_loss, dev_acc, improve))
        #writer.add_scalar("loss/train", loss.item(), total_batch)
        #writer.add_scalar("loss/dev", dev_loss, total_batch)
        #writer.add_scalar("acc/train", train_acc, total_batch)
        #writer.add_scalar("acc/dev", dev_acc, total_batch)

        if epoch - last_improve > require_improvement:
            # 验证集loss超过1epoch没下降，结束训练
            print("No optimization for a long time, auto-stopping...")
            break
    #writer.close()
    test(model, test_iter)

def evaluate(model, data_iter, test=False):
    model.eval()
    loss_total = 0
    predict_all = np.array([], dtype=int)
    labels_all = np.array([], dtype=int)
    with torch.no_grad():
        for batch in data_iter:
            x=batch.text
            labels=batch.label
            if use_cuda:
                x.cuda()
                labels.cuda()
            outputs = model(x)
            loss = F.cross_entropy(outputs, labels)
            loss_total += loss
            labels = labels.data.cpu().numpy()
            predic = torch.max(outputs.data, 1)[1].cpu().numpy()
            labels_all = np.append(labels_all, labels)
            predict_all = np.append(predict_all, predic)
    model.train()
    acc = metrics.accuracy_score(labels_all, predict_all)
    
    if test:
        report = metrics.classification_report(labels_all, predict_all, labels=[0,1],target_names=['pos','neg'], digits=4,output_dict=True)
        confusion = metrics.confusion_matrix(labels_all, predict_all)
        return acc, loss_total / len(data_iter), report, confusion
    
    return acc, loss_total / len(data_iter)


def test(model, test_iter):
    test_acc, test_loss, test_report, test_confusion = evaluate(model, test_iter, test=True)
    msg = 'Test Loss: {0:>5.2},  Test Acc: {1:>6.2%}'
    print(msg.format(test_loss, test_acc))
    print("Precision, Recall and F1-Score...")
    print(test_report)
    print("Confusion Matrix...")
    print(test_confusion)

In [35]:
#lr=1e-3
train(model,train_iterator,valid_iterator,test_iterator)

Epoch:      1,  Train Loss:  0.69,  Train Acc: 50.34%,  Val Loss:   0.7,  Val Acc: 50.94% *
Epoch:      2,  Train Loss:  0.69,  Train Acc: 49.79%,  Val Loss:   0.7,  Val Acc: 52.42% *
Epoch:      3,  Train Loss:  0.69,  Train Acc: 50.13%,  Val Loss:  0.71,  Val Acc: 51.92% 
Epoch:      4,  Train Loss:  0.69,  Train Acc: 50.41%,  Val Loss:  0.71,  Val Acc: 54.28% 
No optimization for a long time, auto-stopping...
Test Loss:   0.8,  Test Acc: 53.72%
Precision, Recall and F1-Score...
{'pos': {'precision': 0.540250756593169, 'recall': 0.49984, 'f1-score': 0.5192603365884064, 'support': 12500}, 'neg': {'precision': 0.5346483066617045, 'recall': 0.57464, 'f1-score': 0.5539232697127434, 'support': 12500}, 'accuracy': 0.53724, 'macro avg': {'precision': 0.5374495316274368, 'recall': 0.53724, 'f1-score': 0.536591803150575, 'support': 25000}, 'weighted avg': {'precision': 0.5374495316274367, 'recall': 0.53724, 'f1-score': 0.536591803150575, 'support': 25000}}
Confusion Matrix...
[[6248 6252]
 [5

In [38]:
#lr=1e-4
train(model,train_iterator,valid_iterator,test_iterator)

Epoch:      1,  Train Loss:  0.69,  Train Acc: 49.44%,  Val Loss:  0.69,  Val Acc: 49.88% *
Epoch:      2,  Train Loss:  0.69,  Train Acc: 50.35%,  Val Loss:  0.69,  Val Acc: 50.76% 
Epoch:      3,  Train Loss:  0.69,  Train Acc: 50.18%,  Val Loss:  0.69,  Val Acc: 50.18% 
No optimization for a long time, auto-stopping...
Test Loss:  0.69,  Test Acc: 50.06%
Precision, Recall and F1-Score...
{'pos': {'precision': 0.5018676627534685, 'recall': 0.15048, 'f1-score': 0.23153618906942391, 'support': 12500}, 'neg': {'precision': 0.5003293807641633, 'recall': 0.85064, 'f1-score': 0.6300663664375443, 'support': 12500}, 'accuracy': 0.50056, 'macro avg': {'precision': 0.501098521758816, 'recall': 0.50056, 'f1-score': 0.4308012777534841, 'support': 25000}, 'weighted avg': {'precision': 0.5010985217588159, 'recall': 0.50056, 'f1-score': 0.43080127775348415, 'support': 25000}}
Confusion Matrix...
[[ 1881 10619]
 [ 1867 10633]]


In [41]:
#dropout=0
train(model,train_iterator,valid_iterator,test_iterator)

Epoch:      1,  Train Loss:  0.69,  Train Acc: 49.61%,  Val Loss:  0.69,  Val Acc: 49.56% *
Epoch:      2,  Train Loss:  0.69,  Train Acc: 50.21%,  Val Loss:  0.69,  Val Acc: 51.24% *
Epoch:      3,  Train Loss:  0.69,  Train Acc: 49.29%,  Val Loss:   0.7,  Val Acc: 49.90% 
Epoch:      4,  Train Loss:  0.69,  Train Acc: 49.94%,  Val Loss:  0.69,  Val Acc: 50.38% 
No optimization for a long time, auto-stopping...
Test Loss:  0.68,  Test Acc: 52.64%
Precision, Recall and F1-Score...
{'pos': {'precision': 0.5794933655006032, 'recall': 0.19216, 'f1-score': 0.2886151997596876, 'support': 12500}, 'neg': {'precision': 0.5157995684488133, 'recall': 0.86056, 'f1-score': 0.6450007495128167, 'support': 12500}, 'accuracy': 0.52636, 'macro avg': {'precision': 0.5476464669747082, 'recall': 0.5263599999999999, 'f1-score': 0.4668079746362521, 'support': 25000}, 'weighted avg': {'precision': 0.5476464669747082, 'recall': 0.52636, 'f1-score': 0.4668079746362521, 'support': 25000}}
Confusion Matrix...
[[

## Results and Analysis

可以看到训练的效果相当差，这与所参照的博客一致，思考可能由以下原因导致：
* 文本长度没有处理，有过长的文本
* 没有使用pack pad等操作

除此之外，还将在后续进行以下优化：
* 对任务的文本长度进行分析
* 使用预训练词向量
* 调整dropout
* 调整momentum